### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by hygoni** [NavyBye/ft_transcendence#312]
IMPORTANT

- [ ] 'Users' button in removed chatroom
- [ ] 'mute', 'give admin' look like kick
- [x] Not automatically free user
- [x] Sending scores:[0,0] - maybe related to firefox
- [x] Not ending game in disconnect
- [x] Ending game but not redirecting
- [ ] Guild Officer cannot kick user

MISC
- [ ] chatroom remove is not real time
- [ ] block dm is receiving but filtered
- [ ]
